DROP TABLE IF EXISTS HISTORIC_WEATHER;

CREATE TABLE HISTORIC_WEATHER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STATION_NAME VARCHAR(200),
  PROVINCE VARCHAR(100),
  RECORD_DATE DATE,
  MEAN_TEMP DECIMAL(8,2),
  HIGHEST_MONTHLY_MAXI_TEMP DECIMAL(8,2),
  LOWEST_MONTHLY_MIN_TEMP DECIMAL(8,2),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TEMPT;

CREATE TABLE TEMPT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STATION_NAME VARCHAR(200),
  PROVINCE VARCHAR(100),
  RECORD_DATE VARCHAR(100),
  MEAN_TEMP DECIMAL(8,2),
  HIGHEST_MONTHLY_MAXI_TEMP DECIMAL(8,2),
  LOWEST_MONTHLY_MIN_TEMP DECIMAL(8,2),
  PRIMARY KEY (ID)
);

INSERT INTO TEMPT (STATION_NAME,PROVINCE,RECORD_DATE,MEAN_TEMP,HIGHEST_MONTHLY_MAXI_TEMP,LOWEST_MONTHLY_MIN_TEMP)
	(SELECT * FROM CSVREAD('classpath:eng-climate-summary.csv'));

INSERT INTO HISTORIC_WEATHER (STATION_NAME,PROVINCE,RECORD_DATE,MEAN_TEMP,HIGHEST_MONTHLY_MAXI_TEMP,LOWEST_MONTHLY_MIN_TEMP)
  (SELECT STATION_NAME,PROVINCE,PARSEDATETIME(RECORD_DATE,'dd/MM/yyyy'), MEAN_TEMP,HIGHEST_MONTHLY_MAXI_TEMP,
    LOWEST_MONTHLY_MIN_TEMP FROM TEMPT);

DROP TABLE IF EXISTS TEMPT;